
//import java.sql.Connection;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.


for(int i=4;i<=9;i++)
            dob=dob+dob1.charAt(i);
        dob=dob+", ";
        for(int i=30;i<=33;i++)
            dob=dob+dob1.charAt(i);
        }

*/
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.regex.*;
//import java.sql.Statement;
import javax.swing.*;


 

/**
 *
 * @author Garvit
 */
public class Bookings extends javax.swing.JFrame {

    String hotelName;
    String roomType;
    String name;
    String location;
    int numOfRooms;
    int numOfGuests;
    int price;
    String username;
    String checkIn;
    String checkOut;
    java.util.Date CheckIn;
    java.util.Date CheckOut;
    java.sql.Date sqlCheckIn;
    java.sql.Date sqlCheckOut;
    int ocf;
    int idf;
    boolean bypass;
    
    
    
    
    public Bookings() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form NewJFrame
     */
    public Bookings(String a,String b,int c,int d,int e,String f,java.sql.Date g,java.sql.Date h, int p,int q,String n,String d1,String d2,String u,java.util.Date dd1,java.util.Date dd2) {
        
       hotelName=a;
   roomType=b;
     numOfRooms=c;
    numOfGuests=d;
    price=e;
    location=f;
    sqlCheckIn=g;
    sqlCheckOut=h;
    ocf=p;
    CheckIn=dd1;
    CheckOut=dd2;
    name=n;
    idf=q;
    checkIn=d1;
    username=u;
    checkOut=d2;
    initComponents();
    
        this.setLocationRelativeTo(null);
    }

    public Bookings(String a,String b,int c,int d,int e,String f,java.sql.Date g,java.sql.Date h, int p,int q,String n,String d1,String d2,String u,java.util.Date dd1,java.util.Date dd2, boolean bipass) {
       bypass=bipass; 
       hotelName=a;
   roomType=b;
     numOfRooms=c;
    numOfGuests=d;
    price=e;
    location=f;
    sqlCheckIn=g;
    sqlCheckOut=h;
    ocf=p;
    CheckIn=dd1;
    CheckOut=dd2;
    name=n;
    idf=q;
    checkIn=d1;
    username=u;
    checkOut=d2;
    initComponents();
    if(bypass==true){
            jLabel2.setText("Waitlist Portal");
            jLabel3.setText("Waitlist Entry Summary");
            jButton1.setText("Confirm Waitlist");
        }
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setVisible(false);

        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setVisible(false);
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(976, 737));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(976, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Booking Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(625, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 980, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Booking Summary");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hotel Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Number of Rooms");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of Guests");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "Aadhar Card", "PAN Card", "Driving License", "Passport" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 247, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Customer:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");
        jLabel14.setText(name);
        jLabel4.setText("Hotel Name: "+hotelName);
        jLabel5.setText("Type of Room: "+roomType);
        jLabel6.setText("Number of Rooms: "+numOfRooms);
        jLabel7.setText("Number of Guests: "+numOfGuests);

        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Select an ID Proof");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 103, 390, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Proof");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 179, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 290, 390, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Note: The same ID should be presented at the Hotel. ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 350, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Sign Out");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 128, 40));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Confirm Booking");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, -1, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Booking Reference");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 750, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Back to Hotel Comparison portal");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 380, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 380, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 450, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("jLabel18");
        String checkin1 = "";
        String checkout1 = "";
        for(int i=4;i<=9;i++)
        checkin1=checkin1+checkIn.charAt(i);
        checkin1=checkin1+", ";
        for(int i=30;i<=33;i++)
        checkin1=checkin1+checkIn.charAt(i);
        for(int i=4;i<=9;i++)
        checkout1=checkout1+checkOut.charAt(i);
        checkout1=checkout1+", ";
        for(int i=30;i<=33;i++)
        checkout1=checkout1+checkOut.charAt(i);

        jLabel17.setText("Check-In: "+checkin1);
        jLabel18.setText("Check-Out: "+checkout1);
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 450, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Payable at time of Check in:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 340, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");
        if(bypass==false)
        jLabel9.setText("Rs. "+price + "/-");
        else
        jLabel9.setText("Rs. "+price + "/- if booking takes place");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 980, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         String s = jComboBox1.getSelectedItem().toString();
        if(s == "--select--")
        {
            jLabel12.setText("");
            jTextField1.setVisible(false);
        }
        else
        {
            jLabel12.setText("Enter " + s + " Number");
            jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    boolean checkIfInDatabase(int roomid, java.util.Date d)
    {
         String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
            boolean f =false;
            String query="select * from r"+roomid;
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
            //System.out.println("Details submitted successfully");
            java.util.Date d1=new java.sql.Date (d.getTime());
            while (rs.next())
            {
                
                if(!d1.toString().equals(((rs.getString(1)))))
                {//System.out.println("Successful login");
                   System.out.println(d1+"          "+rs.getDate(1));
                continue;}
                else
                {
                    f=true;
                    break;
                }
            }
            s.close();
            c.close();
            //this.dispose();
            
            
            
    }
            catch(Exception e){}
            return f;
    }
    
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    public static boolean validateAadharNumber(String aadharNumber){
        Pattern aadharPattern = Pattern.compile("\\d{12}");
        boolean isValidAadhar = aadharPattern.matcher(aadharNumber).matches();
        return isValidAadhar;
    }

public static boolean validatePANNumber(String pan){

Pattern pannum = Pattern.compile("[A-Z]{5}[0-9]{4}[A-Z]{1}");
boolean isValidPan = pannum.matcher(pan).matches();
return isValidPan;
}

public static boolean validateDLNumber(String dl){

Pattern dlnum = Pattern.compile("[A-Z]{2}[0-9]{13}");
boolean isValidDL = dlnum.matcher(dl).matches();
return isValidDL;
}

public static java.util.Date addDays(java.util.Date date, int days) {
		GregorianCalendar cal = new GregorianCalendar();
		cal.setTime(date);
		cal.add(Calendar.DATE, days);
				
		return cal.getTime();
	}

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        String s = jComboBox1.getSelectedItem().toString();
        int flag=0;
        if("--select--".equals(s))
        {
            JOptionPane.showMessageDialog(null, "Select a Valid ID proof");
        }
        else if("Aadhar Card".equals(s) && validateAadharNumber(jTextField1.getText()))
        {          
            flag=1;
        }
        else if("PAN Card".equals(s) && validatePANNumber(jTextField1.getText()))
        {
            flag=1;
        }
        else if("Driving License".equals(s) && validateDLNumber(jTextField1.getText()))
        {
            flag=1;
        }
        else if("Passport".equals(s) && jTextField1.getText().length()>=7 && jTextField1.getText().length()<= 10)
        {
            flag=1;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Enter valid "+ jComboBox1.getSelectedItem().toString()+ " Number");
        }
        if(flag==1)
        {
        
        java.util.Date uuid = new java.util.Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyMMddhhmmssMs");
        String bookref = ft.format(uuid);

        String idno= jTextField1.getText();
        
        
        
        if(bypass==false){JOptionPane.showMessageDialog(null, "Booking Successful!"); 
            jLabel15.setText("Booking Reference Number: " + bookref);
            jLabel15.setVisible(true);
        }

        jButton1.setVisible(false);
        
        if(bypass==false){
       // String name="LOL";
        String url="jdbc:mysql://localhost:3306/sys";
            String mysqluname="root";
            String mysqlpass="mysql";
            String create="CREATE TABLE IF NOT EXISTS r"+idf+"( dates DATE , noOfRoomsAvail int);";
            try{
            Connection c2 = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s2=c2.createStatement();
            s2.execute(create);
            s2.close();
           
            c2.close();
            }
            catch(Exception e){}
       
        try{
        
        java.util.Date temp=CheckIn;
        //System.out.println("LOL1  "+temp);
        java.sql.Date sqlTemp=new java.sql.Date (temp.getTime());
        String query="select * from r"+idf+" ;";
       Connection c1l = DriverManager.getConnection(url,mysqluname,mysqlpass);
           Statement s1l=c1l.createStatement();
           ResultSet rsl = s1l.executeQuery(query);
           
           Connection c1 = DriverManager.getConnection(url,mysqluname,mysqlpass);
           Statement s1=c1.createStatement();
      
            while(temp.before(CheckOut))
            {
                sqlTemp=new java.sql.Date (temp.getTime());
                String query2;
                if(!checkIfInDatabase(idf,temp))
                {
                 query2="insert into r"+idf+" values ('"+sqlTemp+"',"+(ocf-numOfRooms)+");";}
                else
                {
                    rsl.next();int a=rsl.getInt(2);
                    query2="UPDATE r"+idf+" SET noOfRoomsAvail = "+(a-numOfRooms)+" WHERE dates = '"+sqlTemp+"';" ;
                }
                
           int cnt = s1.executeUpdate(query2);
           temp=addDays(temp,1);
            
            }s1.close();
           c1.close();
           
           s1l.close();
           c1l.close();
           
        }
        catch(Exception e){System.out.println(e);}
           // String query2="insert into r"+idf+" values ('"+sqlCheckIn+"','"+sqlCheckOut+"',"+(ocf-numOfRooms)+",\""+uuid+"\");";
            //String query1="UPDATE "+location+" SET noOfRooms = "+(ocf-numOfRooms)+" WHERE hotelid = "+idf+";";
            String query3="insert into bookinglist values (\""+username+"\" , \""+bookref+"\" , \""+location+"\" , \""+hotelName+"\" , \""+roomType+"\" , '"+sqlCheckIn+"' , '"+sqlCheckOut+"' , "+numOfGuests+" , "+numOfRooms+" , \""+s+"\" , \""+idno+"\" , "+price+" , "+idf+" );";
          // System.out.println(query3);
            try{
            Class.forName("com.mysql.jdbc.Driver");
             Connection c3 = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s3=c3.createStatement();
            int cnt1= s3.executeUpdate(query3);
            s3.close();c3.close();
            }
            catch(Exception e){}
            }
        else//code for wlist
        {
            java.sql.Date sqlCheckIn=null;int w = 0; String chekin="",chekout="";
        java.sql.Date sqlCheckOut=null;
        try{
            sqlCheckIn= new java.sql.Date(CheckIn.getTime());
            sqlCheckOut= new java.sql.Date(CheckOut.getTime());
            chekin=checkIn.toString();
            chekout=checkOut.toString();
        }
        catch (Exception e){}

        
      //  int rid = Integer.parseInt(idf);
        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        String query="insert into wlist values ('"+username+"','"+location+"','"+idf+"','"+numOfRooms+"','"+numOfGuests+"','"+sqlCheckIn+"','"+sqlCheckOut+"','"+w+"', \""+s+"\" , \""+idno+"\" ,\""+bookref+"\","+price+");";
        System.out.println(query);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s1=c.createStatement();
            int cnt = s1.executeUpdate(query);;
            s1.close();
            c.close();

        }
        catch(Exception e){}
        
        JOptionPane.showMessageDialog(null, "Successfully enrolled in waiting list");
        
        }
        
            
        
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Details d = new Details(name,username);
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
