/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.sql.*;
import java.util.*;
import java.awt.*;

/**
 *
 * @author User
 */
public class Details extends javax.swing.JFrame {

     DefaultListModel items,items1,items2;
     String location;
     String name;
     String idf;
     String username;
     int numOfRooms,ocf;
        int numOfPeople;
        int price;
         java.util.Date checkIn=null;
        java.util.Date checkOut=null;
        boolean searchClick = false;
     boolean bypass=false;
    
    /**
     * Creates new form Details
     */
    public Details(String n,String u) {
        initComponents();
        this.setLocationRelativeTo(null);
        name=n;
        username =u;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setUndecorated(true);
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        items = new DefaultListModel();
        jList1 =  new JList(items);
        jScrollPane1 = new javax.swing.JScrollPane();
        items1 = new DefaultListModel();

        jList2 = new JList(items1);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookNow = new javax.swing.JButton();
        bookNow.setVisible(false);
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton3.setVisible(false);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setVisible(false);
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setVisible(false);
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel9 = new javax.swing.JLabel();
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jList1.setVisible(false);
        jList2.setVisible(false);
        jLabel18 = new javax.swing.JLabel();
        jLabel18.setVisible(false);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        items2 = new DefaultListModel();
        jList3 = jList3 =  new JList(items2);
        jList3.setVisible(false);
        jLabel16 = new javax.swing.JLabel();
        jLabel16.setVisible(false);
        jButton5 = new javax.swing.JButton();
        jButton5.setVisible(false);
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(1309, 920));
        setPreferredSize(new java.awt.Dimension(1309, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Location:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 128, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goa", "Hyderabad", "Pune", "Delhi", "Mumbai", "Hyderabad1" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 131, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check in date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 177, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check out date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 224, -1, -1));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 184, 120, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 231, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of Rooms:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 271, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Number of people:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 320, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 274, 120, -1));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 323, 120, -1));

        searchButton.setBackground(new java.awt.Color(0, 204, 204));
        searchButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 390, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 255));
        jScrollPane2.setBorder(null);

        jList1.setBackground(new java.awt.Color(0, 0, 255));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jList1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 222, 224));
        jScrollPane2.getViewport().setBackground(Color.BLUE);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jList2.setBackground(new java.awt.Color(0, 0, 255));
        jList2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setSelectionBackground(new java.awt.Color(0, 0, 255));
        jScrollPane1.setViewportView(jList2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 172, 224));
        jScrollPane1.getViewport().setBackground(Color.BLUE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rooms available");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price per night");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, -1, -1));

        bookNow.setBackground(new java.awt.Color(0, 255, 0));
        bookNow.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookNow.setText("Book Now!");
        bookNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookNowMouseClicked(evt);
            }
        });
        bookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNowActionPerformed(evt);
            }
        });
        getContentPane().add(bookNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 860, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("Your Bookings");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 860, -1, 40));

        jButton3.setBackground(new java.awt.Color(255, 204, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Enrol in Waiting list");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, 270, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Reload Page");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 180, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Sign Out");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 860, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 800, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 610, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 500, 300));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Room specifications: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pick a hotel");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 690, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 330, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to hotel comparison portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1609, 80));

        jScrollPane3.setBackground(new java.awt.Color(255, 102, 102));
        jScrollPane3.setBorder(null);

        jList3.setBackground(new java.awt.Color(0, 0, 255));
        jList3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList3.setForeground(new java.awt.Color(255, 255, 255));
        jList3.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jList3.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 182, 224));
        jScrollPane3.getViewport().setBackground(Color.BLUE);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hotels available");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("Confirm Waitlist");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, 290, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1310, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
            if((searchClick == true))
        {
            JOptionPane.showMessageDialog(null, "Cannot change details, reload page to change!","Error" ,JOptionPane.ERROR_MESSAGE);
            jComboBox1.setSelectedItem(location);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public static java.util.Date addDays(java.util.Date date, int days) {
		GregorianCalendar cal = new GregorianCalendar();
		cal.setTime(date);
		cal.add(Calendar.DATE, days);
				
		return cal.getTime();
	}
    
    boolean availability(String id)
    {
        //java.sql.Date sqlCheckIn=null;
       // java.sql.Date sqlCheckOut=null;
       // String chekin="",chekout="";
        
        
        jLabel10.setVisible(false);
        jLabel12.setVisible(false);
        jLabel11.setVisible(false);
        jLabel13.setVisible(false);
        jLabel18.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        
        //System.out.println(id);
         int flag=0;
        try{
         //checkIn=jDateChooser1.getDate();
         //checkOut=jDateChooser2.getDate();
        //sqlCheckIn= new java.sql.Date(checkIn.getTime());
        //sqlCheckOut= new java.sql.Date(checkIn.getTime());
       // chekin=checkIn.toString();
      //  chekout=checkOut.toString();
        }
        catch(Exception e){}
        
        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        java.sql.Date sqlTemp;
            //boolean f =false;
            String query="select * from r"+id;
            try{
             //   
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
//            Statement s=c.createStatement();
//            ResultSet rs = s.executeQuery(query);
            java.util.Date bdate;
            java.util.Date temp=checkIn;
            int flg=3;String n;
            
            // System.out.println(""+temp+" "+checkIn+ " " +checkOut +" " +   "lololololo   "+ addDays(temp,1));
            
            while(temp.before(checkOut))
            {
                
              
            //boolean f =false;
            String query1="select * from r"+id;
            Class.forName("com.mysql.jdbc.Driver");
            Connection c1 = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s1=c1.createStatement();
            ResultSet rs1 = s1.executeQuery(query1);
            
           
             sqlTemp= new java.sql.Date(temp.getTime());
            //ArrayList<String> hotels= new ArrayList<String>();
            while (rs1.next())
            {
                bdate=rs1.getDate(1);
               // bCheckOut=rs.getDate(2);
                n=rs1.getString(2);
              //  System.out.println(n + "  ");
                if(!n.equals(""))
                {    
                    int n1=Integer.parseInt(n);
                    
                if((sqlTemp.toString().equals(bdate.toString())&&(numOfRooms>n1)))
                { 
                    flg=1;
                    break;
                   
                }
                else if ((sqlTemp.toString().equals(bdate.toString())&&(numOfRooms<=n1)))
                {
                    flg =2;
                    break;
                }
                else flg=3;
                
                }
                
               // System.out.println(sqlTemp+"     "+bdate+"     "+flg);
                
               
               // col=0;
            }
            if(flg==1)
                {
                    flag=1;
                    break;
                    
                }
              else
            {
                    temp=addDays(temp,1);
            } 
                    s1.close();
                    c1.close();
                
 }
//            s.close();
//            c.close();
    }
            catch(Exception e){}
            
            
        
        if(flag==1)
            return false;
        return true;
        }
    
    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        location = jComboBox1.getSelectedItem().toString();
        numOfRooms=Integer.parseInt(jComboBox2.getSelectedItem().toString());
        numOfPeople=Integer.parseInt(jComboBox3.getSelectedItem().toString());
        
         jList2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        //java.util.Date checkIn=jDateChooser1.getDate();
        java.sql.Date sqlCheckIn=null;
        jButton3.setVisible(false);
        jLabel15.setVisible(false);
        jLabel13.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel18.setVisible(false);
        jLabel12.setVisible(false);
        jLabel14.setVisible(false);
        //java.util.Date checkOut=jDateChooser2.getDate();
       // java.sql.Date sqlCheckOut= new java.sql.Date(checkIn.getTime());
     //   java.sql.Date sqlCheckIn=null;
        java.sql.Date sqlCheckOut=null;
        String chekin="",chekout="";
       // java.util.Date checkIn=null;
     //   java.util.Date checkOut=null;
        
        long millis=System.currentTimeMillis();  
        java.util.Date currentDate=new java.util.Date(millis);  
        
         String checkin1 = "";
        String checkout1 = "";
        
        try{
         checkIn=jDateChooser1.getDate();
         checkOut=jDateChooser2.getDate();
        sqlCheckIn= new java.sql.Date(checkIn.getTime());
        sqlCheckOut= new java.sql.Date(checkOut.getTime());
        chekin=checkIn.toString();
        chekout=checkOut.toString();
        for(int i=4;i<=9;i++)
            checkin1=checkin1+checkIn.toString().charAt(i);
            checkin1=checkin1+", ";
        for(int i=30;i<=33;i++)
            checkin1=checkin1+checkIn.toString().charAt(i);
        for(int i=4;i<=9;i++)
            checkout1=checkout1+checkOut.toString().charAt(i);
            checkout1=checkout1+", ";
        for(int i=30;i<=33;i++)
            checkout1=checkout1+checkOut.toString().charAt(i);

      //  System.out.println(checkIn);
     //   System.out.println(checkOut);
        }
        catch(Exception e){}
        
        if(chekin.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Check in date","Error" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(chekout.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter a valid Check out date","Error" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(checkIn.before(currentDate))
        {
            JOptionPane.showMessageDialog(null, "Enter a Check in date after today's date","Error" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(checkIn.after(checkOut))
        {
            JOptionPane.showMessageDialog(null, "Check in date cannot be after Check out","Error" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(checkin1.equals(checkout1))
        {
            JOptionPane.showMessageDialog(null, "Check in date cannot be same as Check out date!","Error" ,JOptionPane.ERROR_MESSAGE);
        }
        else
        {
      //  searchButton.setVisible(false);
        searchClick=true;
         String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
            //boolean f =false;
            String query="select * from "+location;
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
     
            int row=0,flag=0;
            //ArrayList<String> hotels= new ArrayList<String>();
            while (rs.next())
            {
               // System.out.println(availability(rs.getString(9))+"   r"+rs.getString(9));
                if((availability(rs.getString(9)))&&numOfRooms<=rs.getInt(10)&&rs.getBoolean(7)){
                //if(false){//System.out.println("Successful login");
                    flag=1;
                   // System.out.println(rs.getString(1)+rs.getString(9));
                   if(!items2.contains(rs.getString(1)))
                    items2.add(row, rs.getString(1));
                   else
                       continue;
                   
                    
                  
             row++;
                }
               
               // col=0;
            }
           // System.out.println("F"+flag);
            if(flag==0)
            {
                jLabel15.setText("Sorry, no rooms are available");
                jLabel15.setVisible(true);
                jLabel10.setText("Click the button below to enrol in the waiting list");
                jLabel10.setVisible(true);
                jButton3.setVisible(true);
            }
            else
            {
                jLabel16.setVisible(true);
                //jLabel7.setVisible(true);
                   // jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                   // jList1.setVisible(true);
                   // jList2.setVisible(true);
                   jList3.setVisible(true);
            }
            //jList1.(hotels.toArray());
            //JList <String> list = new JList(hotels.toArray());
            //getContentPane().add(list);
            s.close();
            c.close();
    }
            catch(Exception e){}
        //jLabel7.setText("LOL");
    }//GEN-LAST:event_searchButtonMouseClicked
    }
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        
        //jLabel13.setIcon(new ImageIcon(("C:"+"/"+"Users"+"/"+"User"+"/"+"Documents"+"/"+"NetBeansProjects"+"/"+"JavaApplication1"+"/"+"src"+"/"+"hotel1.jpg")));
        if(bypass==false)
            bookNow.setVisible(true);
        else
            jButton5.setVisible(true);
        jLabel13.setVisible(true);
        String room= jList1.getSelectedValue();int g=0;
        String hotel=jList3.getSelectedValue();
       
        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
            //boolean f =false;
            String query="select * from "+location;
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
        
            long diff = checkOut.getTime() - checkIn.getTime(); 
        int days=(int)(diff/ 1000 / 60 / 60 / 24);
       
            while (rs.next())
            {
                if(hotel.equals(rs.getString(1))&&room.equals(rs.getString(2)))
                {   //System.out.println("Successful login");
                    jLabel10.setText("Room selected: "+hotel+" " +room+" room");
                    jLabel11.setText("<html>Facilities: "+rs.getString(3)+"</html>");
                    jLabel12.setText("Average rating of "+rs.getString(4)+ " from "+rs.getString(5)+" reviews.");
                    jLabel18.setText("Occupancy: " + rs.getString(11));
                    jLabel13.setIcon(new ImageIcon((rs.getString(8))));
                    jLabel13.setVisible(true);
                    jLabel15.setVisible(true);
                    idf=rs.getString(9);
                    ocf=Integer.parseInt(rs.getString(10));
                   price = days*numOfRooms*Integer.parseInt(rs.getString(6));
                    jLabel14.setText("Total cost for "+days+" days is Rs."+price);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        jLabel14.setVisible(true);
        jLabel18.setVisible(true);
        break;
                    
                }
               // row++;
               // col=0;
            }
            
            //jList1.(hotels.toArray());
            //JList <String> list = new JList(hotels.toArray());
            //getContentPane().add(list);
            s.close();
            c.close();
    }
            catch(Exception e){}
    }//GEN-LAST:event_jList1MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        //location = jComboBox1.getSelectedItem().toString();
        //numOfRooms=Integer.parseInt(jComboBox2.getSelectedItem().toString());
        //numOfPeople=Integer.parseInt(jComboBox3.getSelectedItem().toString());
        bookNow.setVisible(false);
        jLabel9.setText("Click on a room to see more information about the room");
        //java.util.Date checkIn=jDateChooser1.getDate();
        //java.sql.Date sqlCheckIn= new java.sql.Date(checkIn.getTime());
        
        //java.util.Date checkOut=jDateChooser2.getDate();
       // java.sql.Date sqlCheckOut= new java.sql.Date(checkIn.getTime());
     
       java.sql.Date sqlCheckIn=null;
        java.sql.Date sqlCheckOut=null;
        String chekin="",chekout="";
        java.util.Date checkIn=null;
        java.util.Date checkOut=null;
        
        try{
    
        sqlCheckIn= new java.sql.Date(checkIn.getTime());
        sqlCheckOut= new java.sql.Date(checkIn.getTime());
        chekin=checkIn.toString();
        chekout=checkOut.toString();
        }
        catch(Exception e){}
        
   
        
         String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        
        
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        String hotel= jList3.getSelectedValue();
        items.removeAllElements();
        items1.removeAllElements();
            //boolean f =false;
            String query="select * from "+location;
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
   
            int row=0,flag=0;
            //ArrayList<String> hotels= new ArrayList<String>();
            while (rs.next())
            {
                
                //System.out.println(availability(rs.getString(9)));
                if(((availability(rs.getString(9)))&&(hotel.equals(rs.getString(1)))&&(Integer.parseInt(rs.getString(10)))>=numOfRooms)||(bypass==true &&(hotel.equals(rs.getString(1)))&&(Integer.parseInt(rs.getString(10)))>=numOfRooms)){
                //if(false){//System.out.println("Successful login");
                    flag=1;
                  
                    items.add(row, rs.getString(2));
                    items1.add(row,"Rs. "+rs.getString(6));
                 
             row++;
                }
               
               // col=0;
            }
          //  if(bypass=true)
            //    flag=1;
           // System.out.println("F"+flag);
            if(flag==0)
            {
                jLabel15.setText("Sorry, no rooms are available in "+location);
                jLabel15.setVisible(true);
                jLabel10.setText("Click the button below to enrol in the waiting list");
                jLabel10.setVisible(true);
                jButton3.setVisible(true);
                jList1.setVisible(false);
                jList2.setVisible(false);
                jLabel16.setVisible(false);
                jLabel9.setVisible(false);
                jLabel7.setVisible(false);
                bookNow.setVisible(false);
                jLabel8.setVisible(false);
            }
            else
            {
                
                jLabel15.setText("Room specification:");
                jLabel16.setVisible(true);
                jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jList1.setVisible(true);
                    jList2.setVisible(true);
                   //jList3.setVisible(true);
            }
            //jList1.(hotels.toArray());
            //JList <String> list = new JList(hotels.toArray());
            //getContentPane().add(list);
            s.close();
            c.close();
    }
            catch(Exception e){}//System.out.println("Ex"+e);}
        //jLabel7.setText("LOL");
       
      
         
        
        
    }//GEN-LAST:event_jList3MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
      /*  if((searchClick == true))
        {
            JOptionPane.showMessageDialog(null, "Cannot change details, reload page to change!","Error" ,JOptionPane.ERROR_MESSAGE);
            
            
        }*/
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
    
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         if((searchClick == true))
        {
            JOptionPane.showMessageDialog(null, "Cannot change details, reload page to change!","Error" ,JOptionPane.ERROR_MESSAGE);
            jComboBox2.setSelectedItem(""+numOfRooms);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
         if((searchClick == true))
        {
            JOptionPane.showMessageDialog(null, "Cannot change details, reload page to change!","Error" ,JOptionPane.ERROR_MESSAGE);
            jComboBox3.setSelectedItem(""+numOfPeople);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:
         if((searchClick == true))
        {
            JOptionPane.showMessageDialog(null, "Cannot change details, reload page to change!","Error" ,JOptionPane.ERROR_MESSAGE);
            //jComboBox1.setSelectedItem(location);
        }
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        boolean f =false;
        String query="select * from "+location;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
            //System.out.println("Details submitted successfully");

            while (rs.next())
            {
                if(rs.getInt(9)==Integer.parseInt(idf))
                {//System.out.println("Successful login");
                    jLabel13.setIcon(new ImageIcon(rs.getString(8)));

                    break;}
            }
            s.close();
            c.close();

        }
        catch(Exception e){}

    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:

        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        boolean f =false;
        String query="select * from "+location;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
            //System.out.println("Details submitted successfully");

            while (rs.next())
            {
                if(rs.getInt(9)==Integer.parseInt(idf))
                {//System.out.println("Successful login");
                    jLabel13.setIcon(new ImageIcon(rs.getString(12)));

                    break;}
            }
            s.close();
            c.close();

        }
        catch(Exception e){}
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Details d = new Details(name,username);
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

        // numOfRooms=Integer.parseInt(jComboBox2.getSelectedItem().toString());
        //  numOfPeople=Integer.parseInt(jComboBox3.getSelectedItem().toString());
        
        
        bypass=true;
        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        String query="select * from "+location;
        System.out.println(""+location);
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();
            ResultSet rs = s.executeQuery(query);
      
            int row=0;
            jList3.setVisible(true);
            jList1.setVisible(true);
            jLabel16.setVisible(true);
           jLabel9.setVisible(true);
            while (rs.next())
            {
               if(numOfRooms<=rs.getInt(10))
               { items2.add(row, rs.getString(1));
                    row++;}
            }
               
            }
            catch(Exception e){System.out.println(e);}
            
            jButton3.setVisible(false);
            //jButton5.setVisible(true);
            
            

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        YourBookings l = new YourBookings(username,name);
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void bookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNowActionPerformed

    private void bookNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookNowMouseClicked
        // TODO add your handling code here:
        //++++++++++++++++++++++++++++++++++++STORING CHECKIN CHECKOUT DATES++++++++++++++++++++++++++++++++

        java.sql.Date sqlCheckIn=null;
        java.sql.Date sqlCheckOut=null;
        String chekin="",chekout="";
        /* String hotelf=jList3.getSelectedValue();
        String roomf=jList1.getSelectedValue();
        Bookings b = new Bookings(hotelf,roomf,numOfRooms,numOfPeople,price,location,);
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
        try{
            //     java.util.Date checkIn=jDateChooser1.getDate();
            //   java.util.Date checkOut=jDateChooser2.getDate();
            sqlCheckIn= new java.sql.Date(checkIn.getTime());
            sqlCheckOut= new java.sql.Date(checkOut.getTime());
            chekin=checkIn.toString();
            chekout=checkOut.toString();
        }
        catch (Exception e){}

        String hotelf=jList3.getSelectedValue();
        String roomf=jList1.getSelectedValue();
        Bookings b = new Bookings(hotelf,roomf,numOfRooms,numOfPeople,price,location,sqlCheckIn,sqlCheckOut,ocf,Integer.parseInt(idf),name,checkIn.toString(),checkOut.toString(),username,checkIn,checkOut);
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        /*
        String name="LOL";
        String url="jdbc:mysql://localhost:3306/sys";
        String mysqluname="root";
        String mysqlpass="mysql";
        String query="insert into r"+idf+" values ('"+sqlCheckIn+"','"+sqlCheckOut+"');";
        String query1="UPDATE "+location+" SET noOfRooms = "+(ocf-numOfRooms)+" WHERE hotelid = "+idf+";";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s=c.createStatement();

            Connection c1 = DriverManager.getConnection(url,mysqluname,mysqlpass);
            Statement s1=c1.createStatement();

            int cnt = s.executeUpdate(query);
            int cnt1 = s1.executeUpdate(query1);
            //System.out.println("Details submitted successfully");
            s.close();
            c.close();

        }
        catch(Exception e){}*/

    }//GEN-LAST:event_bookNowMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
       
        String hotel=jList3.getSelectedValue().toString();
        String room=jList1.getSelectedValue().toString();
        
        ////////////////////////////////////////////////////
        
        /////////////////////////////////////////////////////////
        
        jButton5.setVisible(false);
        java.sql.Date sqlCheckIn= new java.sql.Date(checkIn.getTime());
        java.sql.Date    sqlCheckOut= new java.sql.Date(checkOut.getTime());
        String hotelf=jList3.getSelectedValue();
        String roomf=jList1.getSelectedValue();
         Bookings b = new Bookings(hotelf,roomf,numOfRooms,numOfPeople,price,location,sqlCheckIn,sqlCheckOut,ocf,Integer.parseInt(idf),name,checkIn.toString(),checkOut.toString(),username,checkIn,checkOut, bypass);
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        //JOptionPane.showMessageDialog(null, "Successfully enrolled in waiting list");
    }//GEN-LAST:event_jButton5MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookNow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
